logging.config=classpath:config/logback-dev.xml
server.port=8080

server.max-http-header-size=20971520

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# 外部服务地址, 测试时会被替换成 mock server
app.github.base-url=https://api.github.com