logging.config=classpath:config/logback-dev.xml
server.port=8080

server.max-http-header-size=20971520

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# 改成你自己的 SMTP 服务
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=你的账号
spring.mail.password=你的密码
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true