logging.config=classpath:config/logback-dev.xml
server.port=8080

server.max-http-header-size=20971520

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# 上传文件的存放目录
app.upload.dir=./upload

# 单个文件与单次请求的大小上限
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
