logging.config=classpath:config/logback-dev.xml
server.port=8080

server.max-http-header-size=20971520

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# WebSocket 风格之外的 GraphQL 传输端点; 默认就是 /graphql, 这里显式写出便于理解
spring.graphql.path=/graphql