logging.config=classpath:config/logback-dev.xml
server.port=8080

server.max-http-header-size=20971520

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# 每个客户端在每个时间窗口内最多允许的请求次数
app.rate-limit.max-requests=5
# 时间窗口长度(毫秒)
app.rate-limit.window-millis=60000